# Generated by Django 5.1.2 on 2024-12-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(upload_to=None)),
                ('followers', models.ManyToManyField(to='accounts.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
